data:
  data_path: ~
  num_train: 4500
  num_val: 500
cfg:
  out_dir: ~
  num_workers: 3
  k: 1
  batch_size: 500
  lr: 5e-4
  eps: 1e-4
  true_random: true
  manual_max_lambda: 0
early_stopping:
  check_every: 3
  eps: 1e-10
